### ISSUE TITLE
Typora 标题段落自动编号功能（包含侧边栏大纲、目录、标题）

### ISSUE THREAD

**Issue by nekosilverfox** [nekosilverfox/blog#3]
### Discussed in https://github.com/NekoSilverFox/blog/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **NekoSilverFox** January 24, 2022</sup>

# 效果图

先不废话，先上效果图。
这里我根据自己的使用习惯改了下，除了一级标题后面有 `.` 其他的最后都是没有的
![在这里插入图片描述](https://img-blog.csdnimg.cn/f79c6dfd54644a06bcf80897ebff8713.png?x-oss-process=image/watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5Yaw57OW6Zuq54u45ZGQ,size_20,color_FFFFFF,t_70,g_se,x_16)
![在这里插入图片描述](https://img-blog.csdnimg.cn/4f2f0d80bfaf4e1fa218ce6a96c77d37.png?x-oss-process=image/watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5Yaw57OW6Zuq54u45ZGQ,size_20,color_FFFFFF,t_70,g_se,x_16)

# 配置方法

**注意：事先说明一下，源代码不是我写的，是基于 2 位国外作者修改的。链接我会放在下面**

[Auto numbering Typora outline](https://pastebin.com/XmYgBbaz)

[TOC Autonumbering for Typora](https://pastebin.com/NYugSbXk)

1. 打开主题文件夹
	![在这里插入图片描述](https://img-blog.csdnimg.cn/742fe26306c84ab1b8addb702fe97688.png?x-oss-process=image/watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5Yaw57OW6Zuq54u45ZGQ,size_20,color_FFFFFF,t_70,g_se,x_16)

2.  在 `themes` 文件夹中新建一个名为 `base.user.css` 的文件，并写入以下代码，并保存：
	```css
	/**************************************
	 * Header Counters in TOC
	 **************************************/
	 
	/* No link underlines in TOC */
	.md-toc-inner {
	    text-decoration: none;
	}
	 
	.md-toc-content {
	    counter-reset: h1toc
	}
	 
	.md-toc-h1 {
	    margin-left: 0;
	    font-size: 1.5rem;
	    counter-reset: h2toc
	}
	 
	.md-toc-h2 {
	    font-size: 1.1rem;
	    margin-left: 2rem;
	    counter-reset: h3toc
	}
	 
	.md-toc-h3 {
	    margin-left: 3rem;
	    font-size: .9rem;
	    counter-reset: h4toc
	}
	 
	.md-toc-h4 {
	    margin-left: 4rem;
	    font-size: .85rem;
	    counter-reset: h5toc
	}
	 
	.md-toc-h5 {
	    margin-left: 5rem;
	    font-size: .8rem;
	    counter-reset: h6toc
	}
	 
	.md-toc-h6 {
	    margin-left: 6rem;
	    font-size: .75rem;
	}
	 
	.md-toc-h1:before {
	    color: black;
	    counter-increment: h1toc;
	    content: counter(h1toc) ". "
	}
	 
	.md-toc-h1 .md-toc-inner {
	    margin-left: 0;
	}
	 
	.md-toc-h2:before {
	    color: black;
	    counter-increment: h2toc;
	    content: counter(h1toc) "." counter(h2toc) " "
	}
	 
	.md-toc-h2 .md-toc-inner {
	    margin-left: 0;
	}
	 
	.md-toc-h3:before {
	    color: black;
	    counter-increment: h3toc;
	    content: counter(h1toc) "." counter(h2toc) "." counter(h3toc) " "
	}
	 
	.md-toc-h3 .md-toc-inner {
	    margin-left: 0;
	}
	 
	.md-toc-h4:before {
	    color: black;
	    counter-increment: h4toc;
	    content: counter(h1toc) "." counter(h2toc) "." counter(h3toc) "." counter(h4toc) " "
	}
	 
	.md-toc-h4 .md-toc-inner {
	    margin-left: 0;
	}
	 
	.md-toc-h5:before {
	    color: black;
	    counter-increment: h5toc;
	    content: counter(h1toc) "." counter(h2toc) "." counter(h3toc) "." counter(h4toc) "." counter(h5toc) " "
	}
	 
	.md-toc-h5 .md-toc-inner {
	    margin-left: 0;
	}
	 
	.md-toc-h6:before {
	    color: black;
	    counter-increment: h6toc;
	    content: counter(h1toc) "." counter(h2toc) "." counter(h3toc) "." counter(h4toc) "." counter(h5toc) "." counter(h6toc) " "
	}
	 
	.md-toc-h6 .md-toc-inner {
	    margin-left: 0;
	}
	 
	/**************************************
	 * Header Counters in Content
	 **************************************/
	 
	/** initialize css counter */
	#write {
	    counter-reset: h1
	}
	 
	h1 {
	    counter-reset: h2
	}
	 
	h2 {
	    counter-reset: h3
	}
	 
	h3 {
	    counter-reset: h4
	}
	 
	h4 {
	    counter-reset: h5
	}
	 
	h5 {
	    counter-reset: h6
	}
	 
	
	.sidebar-content {
	    counter-reset: h1
	}
	 
	.outline-h1 {
	    counter-reset: h2
	}
	 
	.outline-h2 {
	    counter-reset: h3
	}
	 
	.outline-h3 {
	    counter-reset: h4
	}
	 
	.outline-h4 {
	    counter-reset: h5
	}
	 
	.outline-h5 {
	    counter-reset: h6
	}
	 
	.outline-h1>.outline-item>.outline-label:before {
	    counter-increment: h1;
	    content: counter(h1) ". "
	}
	 
	.outline-h2>.outline-item>.outline-label:before {
	    counter-increment: h2;
	    content: counter(h1) "." counter(h2) " "
	}
	 
	.outline-h3>.outline-item>.outline-label:before {
	    counter-increment: h3;
	    content: counter(h1) "." counter(h2) "." counter(h3) " "
	}
	 
	.outline-h4>.outline-item>.outline-label:before {
	    counter-increment: h4;
	    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) " "
	}
	 
	.outline-h5>.outline-item>.outline-label:before {
	    counter-increment: h5;
	    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) " "
	}
	 
	.outline-h6>.outline-item>.outline-label:before {
	    counter-increment: h6;
	    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) " "
	}
	
	
	/** put counter result into headings */
	#write h1:before {
	    counter-increment: h1;
	    content: counter(h1) ". "
	}
	 
	#write h2:before {
	    counter-increment: h2;
	    content: counter(h1) "." counter(h2) " "
	}
	 
	#write h3:before, h3.md-focus.md-heading:before { /*override the default style for focused headings */
	    counter-increment: h3;
	    content: counter(h1) "." counter(h2) "." counter(h3) " "
	}
	 
	#write h4:before, h4.md-focus.md-heading:before {
	    counter-increment: h4;
	    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) " "
	}
	 
	#write h5:before, h5.md-focus.md-heading:before {
	    counter-increment: h5;
	    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) " "
	}
	 
	#write h6:before, h6.md-focus.md-heading:before {
	    counter-increment: h6;
	    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) " "
	}
	 
	/** override the default style for focused headings */
	#write>h3.md-focus:before, #write>h4.md-focus:before, #write>h5.md-focus:before, #write>h6.md-focus:before, h3.md-focus:before, h4.md-focus:before, h5.md-focus:before, h6.md-focus:before {
	    color: inherit;
	    border: inherit;
	    border-radius: inherit;
	    position: inherit;
	    left: initial;
	    float: initial;
	    top: initial;
	    font-size: inherit;
	    padding-left: inherit;
	    padding-right: inherit;
	    vertical-align: inherit;
	    font-weight: inherit;
	    line-height: inherit;
	}
	```

3. 重启 Typora

大功告成</div>
